# Site settings
author: tester
title: hello thank you
header-img: img/home-bg.png
email: cailee.adamson+owdpblogsetup@wework.com
copyright_name: tester
description: > # this means to ignore newlines until "baseurl:"
  blogging
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  caileeowdp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
